remote_theme: pages-themes/modernist@v0.2.0
plugins:
  - jekyll-remote-theme
title: Bimbingan Skripsi
description: Catatan dan panduan untuk mahasiswa bimbingan

baseurl: "/skripsi"     # nama repo Anda
url: "https://galih-hermawan-unikom.github.io"
